services:
  # Backend Spring приложение
  - type: web
    name: spring-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: diplom
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: root
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: 123
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: PORT
        value: 8080

  # Frontend приложение
  - type: web
    name: frontend-app
    env: docker
    dockerfilePath: ./frontend/dockerfile
    dockerContext: ./frontend
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 70

databases:
  - name: diplom
    databaseName: diplom
    user: root
    plan: free

# Дополнительные диски для статических файлов (если нужно)
# disks:
#   - name: postgres-data
#     mountPath: /var/lib/postgresql/data
#     sizeGB: 1
